### ISSUE TITLE
Cursor stays at the starting position during gesture drawing.

### ISSUE THREAD

**Issue by lycsjm** [nine7nine/easystroke#1]
![](https://i.imgur.com/cV1MKkA.png)

take above image as example, when I drawing gesture from  position 1 to position 2, cursor stays on position 1 until gesture end( then it stays 1 or jump to 2 depend on setting).

**Comment by lycsjm** [comment]
on commit 1acb69ecf6a9184ea16b458c3ac544fbe7e9342d , not only mouse stuck, but also trace line disappear.

**Comment by nine7nine** [comment]
cursor jumping is expected behaviour, at least when using a DE where it shows (in Gnome it does not). I could remove / add back the code to make the cusor disappear on draw: but that can cause problems with the nvidia driver (crashing Xorg), not sure i want to do that for your non-composited use-case.

not sure what you mean by trace line disappearing. can you show that? or explain better?

**Comment by lycsjm** [comment]
The first issue didn't really bother me, if it's normal, just keep it that way.

![](https://camo.githubusercontent.com/a8e9f4f1a2938fb311ae2a730da6b5ff13bd5efb389926a1eca26968a012c305/68747470733a2f2f692e696d6775722e636f6d2f6356314d4b6b412e706e67)

The second Issue take my previous image as example. Normally when I draw gesture from  1 to 2, I will see cursor stuck at 1, and a green line draw from  1 to 2.
Since last update, I only see the stuck cursor, no more green line or any indicator. This happens only on my second screen, which is vertical.

**Comment by nine7nine** [comment]
so to verify, without commit: https://github.com/nine7nine/Easystroke-n7n/commit/1acb69ecf6a9184ea16b458c3ac544fbe7e9342d it works fine on your vertical monitor?

**Comment by lycsjm** [comment]
> so to verify, without commit: [1acb69e](https://github.com/nine7nine/Easystroke-n7n/commit/1acb69ecf6a9184ea16b458c3ac544fbe7e9342d) it works fine on your vertical monitor?

 I checked, problem occur at cffca6e4490e61e2a0661fcf1b5c058fece4377e , not 1acb69ecf6a9184ea16b458c3ac544fbe7e9342d .
 Commit 01538792073ca1fbf08baa0bfc468f7a48c7cca7 works fine.

**Comment by nine7nine** [comment]
I can revert that commit. Give me a day or so... i'm a bit busy atm, not in front of my machine.

It doesn't bother me if gtk is using deprecated functions, especially if the modern replacements don't quite work right.

**Comment by nine7nine** [comment]
https://github.com/nine7nine/Easystroke-n7n/commit/34a1f7980f28bac86f9fcedc754808e977bdb521

I've reverted the troublesome commit.

sorry for the delay, I was traveling this week
